### PR TITLE
plugin: improved support for python 3

### PR DESCRIPTION
**Pull request by ricobl**

### CODE REVIEW

**Comment by andrewsmedina** [comment]
@ricobl only change the import is not enough. Will be necessary to change the plugin tests that mock the urlopen.

**Comment by ricobl** [comment]
You're right @andrewsmedina, sorry!

What do you think about moving the plugin to another repository? It will be easier to port to python 3 without messing with the service.

**Comment by ricobl** [comment]
It's ok now @andrewsmedina!

It's worth noting that we don't have a Python 3 build on Travis. It will require more work porting the service to Python 3.

**Comment by andrewsmedina** [comment]
@ricobl thank you!

**Comment by ricobl** [comment]
You're welcome!

**Pull request merged**
